name: Update Gallery

on:
  push:
    paths:
      - "src/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-gallery:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[gallery-update]')"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install ImageMagick
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Run Script to Update Gallery and Thumbnails
        run: |
          chmod +x scripts/generate_gallery.sh
          ./scripts/generate_gallery.sh

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/js/gallery-data.js src/thumbnails
          if ! git diff --staged --quiet; then
            git commit -m "Update gallery and thumbnails [gallery-update]"
            git push
          else
            echo "No changes to commit."
          fi
